# 服务器配置
server:
  port: 8080
  servlet:
    context-path: /api

# 数据库配置
spring:
  datasource:
    url: jdbc:mysql://localhost:3305/agrometeorology?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver

  # JPA配置
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect

  # 文件上传配置
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 15MB

# JWT配置
jwt:
  secret: 45a7sd56asd456as4d65as4d65asd456as4d65as4d65asd456as4d65as4d65asd456as4d65as4d65as4d56sa4d56sa4d
  expirationMs: 86400000

# 文件存储配置
file:
  upload:
    path: uploads
  access:
    url: http://localhost:8080/api/uploads/

# 日志配置
logging:
  level:
    org.agro: DEBUG
    org.hibernate: WARN
    org.hibernate.SQL: WARN
    org.hibernate.type.descriptor.sql: WARN
    org.springframework: INFO

# OpenWeatherMap API配置
openweathermap:
  current-weather-url: https://api.openweathermap.org/data/2.5/weather
  hourly-forecast-url: https://pro.openweathermap.org/data/2.5/forecast/hourly
  daily-forecast-url: https://api.openweathermap.org/data/2.5/forecast/daily
  climate-forecast-url: https://pro.openweathermap.org/data/2.5/forecast/climate
  historical-weather-url: https://history.openweathermap.org/data/2.5/history/city
